create table "users" (
  "id" bigint not null generated by default as identity,
  "email" varchar(45) not null,
  "password" varchar(45) not null,
  "merchant_type" varchar(45) not null,
  "merchant_name" varchar(45) not null,
  "owner_name" varchar(45) not null,
  "address" varchar(45) not null,
  "phone" varchar(45) not null,
  primary key ("id"),
  constraint "id_UNIQUE1"
    unique ("id"),
  constraint "username_UNIQUE"
    unique ("email")
);
create table "discounts" (
  "id" bigint not null generated by default as identity,
  "percentage" int not null,
  "end_date" date null default null,
  "start_date" date null default null,
  primary key ("id"),
  constraint "id_UNIQUE2"
    unique ("id")
);
create table "payment_options" (
  "id" int not null,
  "payment_type" varchar(255) not null,
  "payment_duration" int not null,
  "interest_rate" int not null,
  primary key ("id")
);
create table "product" (
  "product_id" bigint not null,
  "name" varchar(255) null default null,
  "description" varchar(255) null default null,
  "category" varchar(255) null default null,
  "price" varchar(255) null default null,
  "inventory" int null default null,
  "listed_by" bigint null default null,
  primary key ("product_id"),
  constraint "lister"
    foreign key ("listed_by")
    references "users" ("id"),
  index "listerId_idx" ("listed_by")
);
create table "product_discounts" (
  "id_product" bigint not null,
  "id_discount" bigint not null,
  primary key (
    "id_product",
    "id_discount"
  ),
  constraint "id_discount"
    foreign key ("id_discount")
    references "discounts" ("id"),
  constraint "id_product"
    foreign key ("id_product")
    references "product" ("product_id"),
  index "id_discount_idx" ("id_discount")
);
create table "product_payments" (
  "id_product" bigint not null,
  "id_payment" int not null,
  primary key (
    "id_product",
    "id_payment"
  ),
  constraint "id_payments"
    foreign key ("id_payment")
    references "payment_options" ("id"),
  constraint "id_products"
    foreign key ("id_product")
    references "product" ("product_id"),
  index "id_payments_idx" ("id_payment")
);